server:
  port: 8086
  cloud:
    stream:
      bindings:
        output:
          destination: order-fulfillment
          content-type: application/json
        input:
          destination: order-fulfillment
          content-type: application/json
      default-binder: rabbit